### ISSUE TITLE
INFOGRAFÍA DE HILOS EN C#

### ISSUE THREAD

**Issue by IsaHuerta23** [SistemasTecTlaxiaco/infografia-de-hilos-IsaHuerta23#2]
Infografía de Hilos en C#

![HILOS](https://user-images.githubusercontent.com/79929235/117892043-98413b00-b27d-11eb-9f45-c846105d15bd.jpg)

**Comment by IsraelNicolas61** [comment]
Calificación: 18

Calificó: Imanol García e Israel Nicolás

**Comment by josealfredo79** [comment]
Bien hecho y revisado
